### ISSUE TITLE
Exercise 7, Task 8: Exception while executing function: PolicyDocs

### ISSUE THREAD

**Issue by snpdev** [microsoft/MCW-App-modernization#39]
While the PolicyDocsFunction works on my LabVM, I am experiencing a problem with "Exercise 7, Task 8: Test document retrieval from web app". Please review my notes below and let me know if you have any suggestions. Thanks

In App Insights Live Metrics Stream I see a positive trace:
```
Trace: PolicyDocs Function received a request for document 'Daugherty-DAU2RFUEF4KR.pdf'.
```
**However** this is followed by failures:
```
Trace: Executed 'PolicyDocs' (Failed, Id=4363d6d8-99ab-4b38-bd0b-671c9263fa0d)
Exception: Exception while executing function: PolicyDocs <--- Invalid URI: The format of the URI could not be determined.
```
The detailed error stack is shown below.  While remote debugging, I can't see values for `containerUri`, `sasToken` and `uri` due to "Cannot obtain value of the local variable or argument because it is not available at this instruction pointer, possibly because it has been optimized away."
```
Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: PolicyDocs ---> System.UriFormatException: Invalid URI: The format of the URI could not be determined.

   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)

   at System.Uri..ctor(String uriString)

   at Contoso.FunctionApp.PolicyDocsFunction.GetDocumentFromStorage(String policyHolder, String policyNumber) in C:\MCW\MCW-App-modernization-master\Hands-on lab\lab-files\src\Contoso.FunctionApp\PolicyDocsFunction.cs:line 45

   at Contoso.FunctionApp.PolicyDocsFunction.Run(HttpRequest req, String policyHolder, String policyNumber, ILogger log) in C:\MCW\MCW-App-modernization-master\Hands-on lab\lab-files\src\Contoso.FunctionApp\PolicyDocsFunction.cs:line 23

   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 52

   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeAsync(IFunctionInvoker invoker, ParameterHelper parameterHelper, CancellationTokenSource timeoutTokenSource, CancellationTokenSource functionCancellationTokenSource, Boolean throwOnTimeout, TimeSpan timerInterval, IFunctionInstance instance) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 585

   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 532

   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, IFunctionOutputDefinition outputDefinition, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 468

   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 278

   --- End of inner exception stack trace ---

   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 322

   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsyncCore(IFunctionInstanceEx functionInstance, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 117
```

**Comment by timahenning** [comment]
Thank you for reporting this issue.  Please take a moment to review the help and support guidance.  https://microsoftcloudworkshop.com/  We will review your issue soon.

Tim

**Comment by timahenning** [comment]
Mike,

I have not forgoten about this issue.  We have some updates coming out next week that should address all of the issues you created.

Tim

**Comment by kylebunting** [comment]
@snpdev, I am unable to reproduce this issue. Could you verify that you were able to successfully add the application settings required for the function app to run in Azure? These settings are added in Exercise 7, Task 1 using the Azure CLI.

You can verify the settings exist by navigating to the Configuration page of your Azure Function App. You should see settings for `PolicyStorageUrl` and `PolicyStorageSas` listed under Application Settings.

`PolicyStorageUrl` should be the URL you copied for the policies container (e.g., https://<your-storage-account>.blob.core.windows.net/policies).

`PolicyStorageSas` should be the SAS token you created and should look similar to: 

`?sv=2019-02-02&ss=bfqt&srt=sco&sp=rwdlacup&se=2019-10-24T05:35:01Z&st=2019-10-23T21:35:01Z&spr=https&sig=XXs8GEVETsv93FbsqizgCppZd3UsZD%2F3u7hRPenIU5o%3D`

**Comment by snpdev** [comment]
Thanks for looking into this @kylebunting. My workshop resource group is long gone, so I can't verify the settings. Knowing that you could not reproduce the issue, I'll give it another go taking your advice into account.
